name: CI
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Check for duplicated file names
        run: |
          git ls-files --exclude-standard --others --cached --no-empty-directory | sort -f > files.txt
          uniq -di files.txt > duplicates.txt
          if [[ -s duplicates.txt ]]; then
            echo "Found files with the same name:"
            cat duplicates.txt
            exit 1
          fi

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Npm install
        run: npm ci

      - name: Npx run
        run: npx cypress run --headless

      - name: Create test summary
        uses: test-summary/action@v1.0
        if: always()
        with:
          paths: reports/*.xml
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "reports/*.xml"

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
